# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy website

on:
  push:
    branches: [ "main" ]

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
 build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Netlify
      run: npm install netlify-cli@17.10.1 -g
        
    - name: Install Dependencies
      run: npm ci

    - name: Build project
      run: npm run build
      
    - name: Deploy to Netlify
      id: cicd-react
      run: |
        prod_flag=""
        if [ "$BRANCH_NAME" = "main" ]; then prod_flag="--prod"; fi
        netlify deploy \
          --dir dist \
          --site ${{ secrets.NETLIFY_SITE_ID }} \
          --auth ${{ secrets.NETLIFY_API_TOKEN }} \
          $prod_flag 

    
